"""is_active, replaced_doc_id_cols

Revision ID: 426afa44a040
Revises: 1648d6bc1fbf
Create Date: 2026-01-17 23:41:26.773576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426afa44a040'
down_revision: Union[str, Sequence[str], None] = '1648d6bc1fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('replaced_by_doc_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'replaced_by_doc_id')
    op.drop_column('documents', 'is_active')
    # ### end Alembic commands ###
