"""add document processing and claim action_required

Revision ID: 5ffd3226c8e5
Revises: 51c5c292e637
Create Date: 2025-12-27 12:12:59.897078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ffd3226c8e5'
down_revision: Union[str, Sequence[str], None] = '51c5c292e637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('action_required', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('processing_stage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_stage')
    op.drop_column('claims', 'action_required')
    # ### end Alembic commands ###
